# Generated by Django 3.1.7 on 2021-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotion_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='brand_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
